### ISSUE TITLE
RuntimeError: can not access known pictory configuration

### ISSUE THREAD

**Issue by savnik** [naruxde/revpimodio2#10]
I get a runtime error when trying to initialize the lib.

I have a function in a class which is initializing the hardware:
```
def __init__(self):
        # Initialize hardware
        self.revpi = revpimodio2.RevPiModIO(autorefresh=True)
```
The problem is that revpimodio2 is trying to access pictory configurations at /etc/revpi/config.rsc.
I'am running this on a Balena OS in a docker container. Both Balena OS and the Docker Container do not have this directory `/etc/revpi/`.
Where can i find this dependency which is putting the configuration file in this path?

Full Error:
```
30.01.21 10:07:34 (+0100)  application  Traceback (most recent call last):
30.01.21 10:07:34 (+0100)  application    File "/src/Hardware.py", line 110, in <module>
30.01.21 10:07:34 (+0100)  application      hardware = Hardware()
30.01.21 10:07:34 (+0100)  application    File "/src/Hardware.py", line 23, in __init__
30.01.21 10:07:34 (+0100)  application      self.revpi = revpimodio2.RevPiModIO(autorefresh=True)
30.01.21 10:07:34 (+0100)  application    File "/usr/local/lib/python3.7/dist-packages/revpimodio2/modio.py", line 128, in __init__
30.01.21 10:07:34 (+0100)  application      self._configure(self.get_jconfigrsc())
30.01.21 10:07:34 (+0100)  application    File "/usr/local/lib/python3.7/dist-packages/revpimodio2/modio.py", line 918, in get_jconfigrsc
30.01.21 10:07:34 (+0100)  application      "".format(", ".join(lst_rsc))
30.01.21 10:07:34 (+0100)  application  RuntimeError: can not access known pictory configurations at /etc/revpi/config.rsc, /opt/KUNBUS/config.rsc - use 'configrsc' parameter so specify location
```

**Comment by naruxde** [comment]
You can add `configrsc` or even `procimg` to the RevPiModIO call to point to another file location of piCtory configuration or even the piCtonrol0 device.

Just add `revpimodio2.RevPiModIO(autorefresh=True, configrsc="/path/to/your/config.rsc")` and ModIO will use that file to get the configuration.

**Comment by savnik** [comment]
Thanks I realised when running balena os there is no default config.rsc. When testing this on the OS provided by kunbus there is a default config file but then flashing with balena os there is not. Hence it did work out of the box when testing using the OS kunbus provided and I though I needed to install a dependency to get it working.
