### ISSUE TITLE
Accessing DIO/Analog from within the Docker Container 

### ISSUE THREAD

**Issue by fullStackDev316** [naruxde/revpimodio2#20]
We are in the process of trying to use docker on the RevPi's. We would like to access the I/O module data from the container. I have read some documentation on the RevPi website but some things are still not clear and I was hoping to get some help/guidance. 

Can this library be used within the container to get the data from the I/O modules? I have found a few mentions of adding a device (device=/dev/piControl0) to the container and sharing of the pictory config. Are these the only dependencies that we would have to share? 

Any guidance would really help. Thanks in advance!

**Comment by naruxde** [comment]
You can use the library, it is a pure python library and uses build in modules of python3. If you want to use it inside a docker container, you just have to link the /dev/piControl0 device and the piCotry file inside of your container. If you use alternative path names for this files, you have to tell RevPiModIO the names by adding `procimg` and `configrsc` parameter.

`rpi = revpimodio2.RevPiModIO(procimg="/inside_docker/piControl0", configrsc="inside_docker/config.rsc")`

**Comment by fullStackDev316** [comment]
@naruxde : I was able to get docker container to work by passing piControl0 as --device into the container. We are now looking into using docker swarm. Unfortunately, docker swarm does not support passing --device. We tried a few other options but we are getting stuck one way or the other. 
Is there a different way to make this work? We ran with elevated permissions and we still get the following error.
`
File "/usr/local/lib/python3.9/site-packages/revpimodio2/modio.py", line 132, in __init__
    self._configure(self.get_jconfigrsc())
  File "/usr/local/lib/python3.9/site-packages/revpimodio2/modio.py", line 196, in _configure
    self._myfh = self._create_myfh()
  File "/usr/local/lib/python3.9/site-packages/revpimodio2/modio.py", line 465, in _create_myfh
    return open(self._procimg, "r+b", 0)
PermissionError: [Errno 1] Operation not permitted: '/dev/piControl0'
`

Any guidance would really help. Thanks in advance!

**Comment by nbuchwitz** [comment]
Please try a privileged container
