### ISSUE TITLE
troubleshooting help, patch included

### ISSUE THREAD

**Issue by kjkoster** [naruxde/revpimodio2#21]
Hi,

When I was adding two AIO modules to my Pi I got a generic error message. I created a tiny patch that improves that error message to include troubleshooting details. I hope this helps someone in the future.

Kees Jan

[devices_names.patch.txt](https://github.com/naruxde/revpimodio2/files/8402862/devices_names.patch.txt)

**Comment by nbuchwitz** [comment]
Hi kees please have a look at my answer in the forum

Nicolai

**Comment by naruxde** [comment]
Hi Kees!

I like that! Will apply your patch right now and try to add the position number as well in the message!

Thanks a lot!

**Comment by kjkoster** [comment]
Glad to help.
