### ISSUE TITLE
Error when using replace_io() function 

### ISSUE THREAD

**Issue by NSURLSession0** [naruxde/revpimodio2#24]
I'm trying to use the replace_io() function so I can set custom IO-names without using PiCtory, but I'm having a hard time doing so. I'm not sure if I'm doing something wrong or if there's a bug in RevPiModio itself. 

I get the following error when running the code below: 

**Error:**
```
Traceback (most recent call last):
  File "plc_program.py", line 31, in <module>
    program = Program()
  File "plc_program.py", line 20, in __init__
    self.rpi.io.InBit_1.replace_io('variable_name', '?', bit=0)
AttributeError: 'IOBase' object has no attribute 'replace_io'
```

**Code:**
```python
#!/usr/bin/python3
# -*- coding: utf-8 -*-

import revpimodio2
import logging

class Program:

    def __init__(self):
        # Logging
        logging.basicConfig(level=logging.INFO)

        # Instantiate RevPiModIO
        self.rpi = revpimodio2.RevPiModIO(autorefresh=True)

        # Handle SIGINT / SIGTERM to exit program correctly
        self.rpi.handlesignalend(self.cleanup_revpi)

        # Replace IO
        self.rpi.io.InBit_1.replace_io('variable_name', '?', bit=0)
    
    def start(self):
        logging.info("Start")
        self.cleanup_revpi()
        self.rpi.mainloop(blocking=False)

    def cleanup_revpi(self):
        logging.info("Cleanup RevPi")

if __name__ == "__main__":
    program = Program()
    program.start()
```

**PiCtory Configuration:** 
<img width="1451" alt="Scherm­afbeelding 2023-06-14 om 21 46 29" src="https://github.com/naruxde/revpimodio2/assets/2742292/c333a7a4-dab1-497d-8d7b-fc29fec6d226">

RevPiModio version: `2.5.10-1+revpi10`

**Comment by naruxde** [comment]
The replace_io function can only be used for virtual devices. It is designed to decompose bytes into bits, for example, and to combine bytes to larger data types. A general renaming of the IOs can only take place via PiCtory.
