### ISSUE TITLE
Setting output value sometimes fails when using `autorefresh=True`

### ISSUE THREAD

**Issue by FMeinicke** [naruxde/revpimodio2#25]
Hi there,

I've encountered some strange behavior when setting the output value of a DIO module. Consider the following code:

```py
from __future__ import annotations

import logging
import time

import revpimodio2 as rp2
from revpimodio2 import io as rp2_io

logger = logging.getLogger(__name__)

LOGGING_FORMAT = (
    "%(asctime)s [%(threadName)-{thread_name_len}.{thread_name_len}s] %(levelname)-8s| "
    "%(name)s %(module)s.%(funcName)s (%(lineno)s): %(message)s"
)
LOGGING_LEVEL = logging.DEBUG

logging.basicConfig(format=LOGGING_FORMAT.format(thread_name_len=12), level=LOGGING_LEVEL)


rev_pi = rp2.RevPiModIO(autorefresh=True, shared_procimg=True)
rev_pi.mainloop(blocking=False)

output_port: rp2_io.IOBase = rev_pi.io["O_17"]

def set_output(value: bool):
    logger.info(f"Setting output value to {value}")
    start = time.perf_counter_ns()
    output_port.value = value
    end = time.perf_counter_ns()

    total_write_time = (end - start) / 1000
    logger.debug(f"writing took {total_write_time} µs")

    # wait to ensure that at least one cycle has been completed
    time.sleep(rev_pi.cycletime / 1000)

    for i in range(100):
        if output_port.value != value:
            logger.debug(f"{i=}: current output value {output_port.value}, should be {value}")
        time.sleep(0.01)


try:
    while True:
        set_output(True)
        time.sleep(0.1)
        set_output(False)
        time.sleep(0.1)
except KeyboardInterrupt:
    print()

rev_pi.exit()
```

This example simply toggles the output `O_17` between `True` and `False`. It uses `autorefresh=True` and `mainloop(blocking=False)` so that I can do `ouput.value = value` and don't have to take care of writing or reading the process image myself as this is done by the library in a separate thread.

However, sometimes it happens that the output value is not set correctly. When this happens the script will log a bunch of `i=xx: current output value True, should be False` messages. Since the output is switching a valve I can also hear that the valve did not switch when the script shows that the output was not correctly set.  
To me, this looks like the process image is sometimes not correctly updated.

To confirm that there was nothing else wrong with the script I also tested the behavior when not using `autorefresh` and `mainloop()` but rather reading/writing the process image explicitly:
```py
#...
rev_pi = rp2.RevPiModIO(autorefresh=False, shared_procimg=True)  # <<
#...
def set_output(value: bool):
    logger.info(f"Setting output value to {value}")

    start = time.perf_counter_ns()
    output_port.value = value
    rev_pi.writeprocimg()             # <<
    end = time.perf_counter_ns()
    #...
    for i in range(100):
        rev_pi.readprocimg()          # <<
        if output_port.value != value:
            logger.debug(f"{i=}: current output value {output_port.value}, should be {value}")
        time.sleep(0.01)
#...
```

<details><summary>Full script for completeness</summary>

```py
from __future__ import annotations

import logging
import time

import revpimodio2 as rp2
from revpimodio2 import io as rp2_io

logger = logging.getLogger(__name__)

LOGGING_FORMAT = (
    "%(asctime)s [%(threadName)-{thread_name_len}.{thread_name_len}s] %(levelname)-8s| "
    "%(name)s %(module)s.%(funcName)s (%(lineno)s): %(message)s"
)
LOGGING_LEVEL = logging.DEBUG

logging.basicConfig(format=LOGGING_FORMAT.format(thread_name_len=12), level=LOGGING_LEVEL)


rev_pi = rp2.RevPiModIO(autorefresh=False, shared_procimg=True)

output_port: rp2_io.IOBase = rev_pi.io["O_17"]

def set_output(value: bool):
    logger.info(f"Setting output value to {value}")

    start = time.perf_counter_ns()
    output_port.value = value
    mid = time.perf_counter_ns()
    rev_pi.writeprocimg()
    end = time.perf_counter_ns()

    total_write_time = (end - start) / 1000
    set_time = (mid - start) / 1000
    write_time = (end - mid) / 1000
    logger.debug(f"writing took {total_write_time} µs ({set_time} µs + {write_time} µs)")

    for i in range(100):
        rev_pi.readprocimg()
        if output_port.value != value:
            logger.debug(f"{i=}: current output value {output_port.value}, should be {value}")
        time.sleep(0.01)


try:
    while True:
        set_output(True)
        time.sleep(0.1)
        set_output(False)
        time.sleep(0.1)
except KeyboardInterrupt:
    print()
```

</details>

I let this script run for over an hour without any problems whereas the other script would already show an error after a couple of seconds or at most a few minutes.

So my question is, am I doing something wrong in the `autorefresh` case? I can work with having to read/write the process image explicitly in this case but it seems to me that the `autorefresh` functionality should be just as reliable.

Note that I have to use `shared_procimg=True` because I have multiple Python scripts that need to access the process image but they are controlling different inputs/outputs of the DIO module.  
Could this have an impact, maybe?

**Comment by FMeinicke** [comment]
Because I suspected that the `shared_procimg=True` had something to do with the behavior I see, I ran the original test again (with `autorefresh=True` and `mainloop(blocking=False)`) but this time without any of the other Python processes running that also access the process image.  
In this case, I did not see the described behavior, the output was always set as expected.

So, to summarize, I only see a wrong output value if I use `autorefresh=True` and `mainloop(blocking=False)` **and** I have other processes that access the process image running as well (even though these other processes only operate on different I/Os, no two processes operate on the same I/Os).

**Comment by naruxde** [comment]
Thank you very much for the detailed examination @FMeinicke!

I will set up a test setup immediately and recreate the problem with your scripts!

You will then receive feedback immediately!

**Comment by naruxde** [comment]
Hi @FMeinicke!

It looks like we found the error. I think I will publish an RC this week. Could you then test the version against your systems to make sure that the error is fixed?

**Comment by FMeinicke** [comment]
Hey @naruxde,
that sounds awesome! I will see that I can test your fix as soon as possible.  
Thank you for taking the time to look into this issue.

**Comment by naruxde** [comment]
Okay, you can find the fix in this branch https://github.com/naruxde/revpimodio2/tree/fix/shared-procimg-values, if you just want to copy the revpimodio2 directory to your project. Please make sure to check revpimodio2.__version__ for "2.6.1rc1" ;)

Or a prerelease of the debian Package. You can install this on the system, the final 2.6.1 will replace the rc automatically.

[http://revpimodio.org/dnl/python3-revpimodio2_2.6.1~1-1_all.deb]()

**Comment by FMeinicke** [comment]
Perfect, I'll test this ASAP next week.

**Comment by FMeinicke** [comment]
Hey @naruxde,
just to let you know, I won't be able to test your fix before the end of next week (at the earliest), most likely it'll be the beginning of the week after because the system with the RevPi is currently in the process of being moved to a different location.  
I'll get back to you as soon as I could properly test the fix with our system.
