### ISSUE TITLE
Bug RevPi Connect 4: Controlling relais output with x2out

### ISSUE THREAD

**Issue by aq-daniel** [naruxde/revpimodio2#28]
Hello,
thank you for developing this great library. I'm using it to control a Connect4. 

Unfortunately there seems to be an issue controlling the relais contact x2out:
At the moment switching the property 'core.x2out.value' doesn't control the relais, but instead switches the LED A3 to red on the connect 4. In my opinion this is due to a wrong assignment of the property 'x2out' to bit 6 of the RevPiLED-Word (see line 1301 [src/revpimodio2/device.py](https://github.com/naruxde/revpimodio2/blob/9741d13514b437b11299c4b8c4a889efc0aa8650/src/revpimodio2/device.py#L1301).

On the Connect4 the relais is controlled by bit 0 of the RevPiOutput-Word. (see last paragraph in [documentation](https://revolutionpi.com/de/tutorials/ubersicht-revpi-connect/relaiskontakt))

I would appreciate a quick fix for this. Thank you!

**Comment by naruxde** [comment]
#29 will fix this. We have an RC version for testing https://revpimodio.org/dnl/revpimodio2/python3-revpimodio2_2.7.2~rc1-1_all.deb
